import { Task, Project, Area, Contact, FileItem } from '@/types';

export const MOCK_AREAS: Area[] = [
  { id: 'area-bf-1', workspaceId: 'byron-film', name: 'Production', color: '#F59E0B' },
  { id: 'area-bf-2', workspaceId: 'byron-film', name: 'Post-Production', color: '#3B82F6' },
  { id: 'area-bf-3', workspaceId: 'byron-film', name: 'Business Dev', color: '#10B981' },
  { id: 'area-ko-1', workspaceId: 'korus', name: 'Sales', color: '#8B5CF6' },
  { id: 'area-ko-2', workspaceId: 'korus', name: 'Operations', color: '#3B82F6' },
  { id: 'area-ko-3', workspaceId: 'korus', name: 'Marketing', color: '#EC4899' },
];

export const MOCK_TASKS: Task[] = [
  // Byron Film tasks
  {
    id: 'task-1',
    workspaceId: 'byron-film',
    title: 'Scout locations for Alpine commercial',
    description: 'Need to find 3 mountain locations within 2hrs of Byron Bay',
    status: 'pre-prod',
    priority: 'high',
    dueDate: '2026-03-10',
    assignee: 'Charlie',
    tags: ['commercial', 'alpine'],
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-02-20T14:00:00Z',
  },
  {
    id: 'task-2',
    workspaceId: 'byron-film',
    title: 'Edit reel for Pacific Wellness campaign',
    description: 'Cut 90s hero video + 3x 15s socials',
    status: 'post-prod',
    priority: 'urgent',
    dueDate: '2026-03-05',
    assignee: 'Charlie',
    tags: ['wellness', 'social'],
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-22T16:00:00Z',
  },
  {
    id: 'task-3',
    workspaceId: 'byron-film',
    title: 'Invoice Byron Surf Festival',
    status: 'invoiced',
    priority: 'medium',
    tags: ['admin', 'invoice'],
    createdAt: '2026-02-15T08:00:00Z',
    updatedAt: '2026-02-15T08:00:00Z',
  },
  {
    id: 'task-4',
    workspaceId: 'byron-film',
    title: 'Concept development — Spring lookbook',
    status: 'backlog',
    priority: 'low',
    tags: ['creative', 'lookbook'],
    createdAt: '2026-02-18T11:00:00Z',
    updatedAt: '2026-02-18T11:00:00Z',
  },
  {
    id: 'task-5',
    workspaceId: 'byron-film',
    title: 'Drone footage review — Sunrise sessions',
    status: 'review',
    priority: 'high',
    dueDate: '2026-03-02',
    assignee: 'Charlie',
    tags: ['drone', 'review'],
    createdAt: '2026-02-20T09:00:00Z',
    updatedAt: '2026-02-24T12:00:00Z',
  },
  // KORUS tasks
  {
    id: 'task-6',
    workspaceId: 'korus',
    title: 'Meridian Group — initial call',
    description: 'First discovery call to qualify opportunity',
    status: 'lead',
    priority: 'medium',
    dueDate: '2026-03-01',
    assignee: 'Charlie',
    tags: ['enterprise'],
    createdAt: '2026-02-20T10:00:00Z',
    updatedAt: '2026-02-20T10:00:00Z',
  },
  {
    id: 'task-7',
    workspaceId: 'korus',
    title: 'Apex Partners — proposal deck',
    description: 'Prepare and send proposal for Q2 engagement',
    status: 'proposal',
    priority: 'urgent',
    dueDate: '2026-03-03',
    assignee: 'Charlie',
    tags: ['proposal', 'priority'],
    createdAt: '2026-02-18T09:00:00Z',
    updatedAt: '2026-02-24T15:00:00Z',
  },
  {
    id: 'task-8',
    workspaceId: 'korus',
    title: 'Solaris Tech — contract negotiation',
    status: 'negotiation',
    priority: 'high',
    dueDate: '2026-03-07',
    assignee: 'Charlie',
    tags: ['contract'],
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-02-23T11:00:00Z',
  },
  {
    id: 'task-9',
    workspaceId: 'korus',
    title: 'BlueSky Ventures — onboarding',
    status: 'won',
    priority: 'medium',
    tags: ['onboarding'],
    createdAt: '2026-02-10T09:00:00Z',
    updatedAt: '2026-02-20T14:00:00Z',
  },
  {
    id: 'task-10',
    workspaceId: 'korus',
    title: 'Redline Capital — qualify requirements',
    status: 'qualification',
    priority: 'high',
    dueDate: '2026-03-05',
    assignee: 'Charlie',
    tags: ['finance'],
    createdAt: '2026-02-22T09:00:00Z',
    updatedAt: '2026-02-22T09:00:00Z',
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    workspaceId: 'byron-film',
    name: 'Pacific Wellness Campaign',
    description: 'Full video production for Pacific Wellness brand',
    status: 'active',
    startDate: '2026-02-01',
    endDate: '2026-03-15',
    budget: 12000,
  },
  {
    id: 'proj-2',
    workspaceId: 'byron-film',
    name: 'Alpine Commercial Series',
    description: '3-part commercial series for outdoor brand',
    status: 'active',
    startDate: '2026-02-15',
    endDate: '2026-04-01',
    budget: 18000,
  },
  {
    id: 'proj-3',
    workspaceId: 'byron-film',
    name: 'Byron Surf Festival Coverage',
    description: 'Event coverage and highlight reel',
    status: 'completed',
    startDate: '2026-01-20',
    endDate: '2026-02-10',
    budget: 5500,
  },
  {
    id: 'proj-4',
    workspaceId: 'korus',
    name: 'Q1 Enterprise Push',
    description: 'Close 5 enterprise deals in Q1',
    status: 'active',
    startDate: '2026-01-01',
    endDate: '2026-03-31',
  },
];

export const MOCK_CONTACTS: Contact[] = [
  {
    id: 'contact-1',
    workspaceId: 'korus',
    name: 'Sarah Chen',
    email: 'sarah@apexpartners.com',
    phone: '+61 2 9000 1111',
    company: 'Apex Partners',
    role: 'CEO',
    address: '1 Martin Place, Sydney NSW 2000',
    website: 'https://apexpartners.com',
    notes: 'Met at Sydney Tech Summit. Very interested in Q2 engagement. Follow up after proposal review.',
    pipelineStage: 'proposal',
    tags: ['enterprise', 'priority'],
    lastContact: '2026-02-24',
  },
  {
    id: 'contact-2',
    workspaceId: 'korus',
    name: 'Marcus Webb',
    email: 'mwebb@solaristech.io',
    phone: '+61 3 9000 2222',
    company: 'Solaris Tech',
    role: 'COO',
    address: '120 Collins Street, Melbourne VIC 3000',
    website: 'https://solaristech.io',
    notes: 'Contract negotiation in final stages. Legal team reviewing terms.',
    pipelineStage: 'negotiation',
    tags: ['tech', 'contract'],
    lastContact: '2026-02-23',
  },
  {
    id: 'contact-3',
    workspaceId: 'korus',
    name: 'Priya Sharma',
    email: 'priya@blueskyventures.co',
    phone: '+61 7 9000 3333',
    company: 'BlueSky Ventures',
    role: 'Partner',
    address: '333 Ann Street, Brisbane QLD 4000',
    website: 'https://blueskyventures.co',
    notes: 'Deal closed. Onboarding scheduled for March.',
    pipelineStage: 'won',
    tags: ['vc', 'won'],
    lastContact: '2026-02-20',
  },
  {
    id: 'contact-4',
    workspaceId: 'korus',
    name: 'James Harrington',
    email: 'james@meridiangroup.au',
    phone: '+61 2 9001 4444',
    company: 'Meridian Group',
    role: 'Director',
    address: '50 Bridge Street, Sydney NSW 2000',
    website: 'https://meridiangroup.au',
    notes: 'Initial discovery call booked. Enterprise requirements — 50+ seats.',
    pipelineStage: 'lead',
    tags: ['enterprise'],
    lastContact: '2026-02-20',
  },
  {
    id: 'contact-5',
    workspaceId: 'korus',
    name: 'Elena Voss',
    email: 'evoss@redlinecapital.com',
    phone: '+61 2 9002 5555',
    company: 'Redline Capital',
    role: 'Managing Partner',
    address: '200 George Street, Sydney NSW 2000',
    website: 'https://redlinecapital.com',
    notes: 'Qualification call completed. High budget, complex requirements.',
    pipelineStage: 'qualification',
    tags: ['finance', 'high-value'],
    lastContact: '2026-02-22',
  },
  {
    id: 'contact-6',
    workspaceId: 'byron-film',
    name: 'Tom Alcott',
    email: 'tom@pacificwellness.com.au',
    phone: '+61 2 6685 6666',
    company: 'Pacific Wellness',
    role: 'Marketing Director',
    address: '12 Jonson Street, Byron Bay NSW 2481',
    website: 'https://pacificwellness.com.au',
    notes: 'Active client. Campaign in post-production.',
    pipelineStage: 'active',
    tags: ['client', 'wellness'],
    lastContact: '2026-02-22',
  },
];

export const KORUS_METRICS = {
  revenue: {
    current: 247500,
    previous: 198000,
    label: 'Revenue MTD',
  },
  projects: {
    active: 4,
    total: 12,
    label: 'Active Projects',
  },
  leads: {
    active: 7,
    qualified: 3,
    label: 'Active Leads',
  },
  wonDeals: {
    count: 3,
    value: 94000,
    label: 'Deals Won (Q1)',
  },
};

export const MOCK_FILES: FileItem[] = [
  // ── BYRON FILM ──────────────────────────────────────────────────────
  // Root folders
  { id: 'bf-projects',     workspaceId: 'byron-film', name: 'Projects',     type: 'folder', parentId: null, modifiedAt: '2026-02-24T10:00:00Z', owner: 'Charlie' },
  { id: 'bf-deliverables', workspaceId: 'byron-film', name: 'Deliverables', type: 'folder', parentId: null, modifiedAt: '2026-02-22T14:00:00Z', owner: 'Charlie' },
  { id: 'bf-contracts',    workspaceId: 'byron-film', name: 'Contracts',    type: 'folder', parentId: null, modifiedAt: '2026-02-15T09:00:00Z', owner: 'Charlie' },
  { id: 'bf-assets',       workspaceId: 'byron-film', name: 'Assets',       type: 'folder', parentId: null, modifiedAt: '2026-01-30T11:00:00Z', owner: 'Charlie' },

  // Projects / Alpine Commercial
  { id: 'bf-p-alpine',       workspaceId: 'byron-film', name: 'Alpine Commercial', type: 'folder', parentId: 'bf-projects',  modifiedAt: '2026-02-24T10:00:00Z', owner: 'Charlie' },
  { id: 'bf-alpine-raw',     workspaceId: 'byron-film', name: 'Raw Footage',       type: 'folder', parentId: 'bf-p-alpine',  modifiedAt: '2026-02-20T08:00:00Z', owner: 'Charlie' },
  { id: 'bf-alpine-edits',   workspaceId: 'byron-film', name: 'Edits',             type: 'folder', parentId: 'bf-p-alpine',  modifiedAt: '2026-02-24T10:00:00Z', owner: 'Charlie' },
  { id: 'bf-alpine-brief',   workspaceId: 'byron-film', name: 'creative_brief.pdf',       type: 'pdf',    parentId: 'bf-p-alpine',     size: 1258291,    modifiedAt: '2026-02-01T09:00:00Z', owner: 'Charlie' },
  { id: 'bf-alpine-drone',   workspaceId: 'byron-film', name: 'drone_sunrise_01.mp4',     type: 'video',  parentId: 'bf-alpine-raw',   size: 2254857830, modifiedAt: '2026-02-18T07:30:00Z', owner: 'Charlie' },
  { id: 'bf-alpine-handheld',workspaceId: 'byron-film', name: 'handheld_b_roll.mp4',      type: 'video',  parentId: 'bf-alpine-raw',   size: 933232640,  modifiedAt: '2026-02-18T08:45:00Z', owner: 'Charlie' },
  { id: 'bf-alpine-v1',      workspaceId: 'byron-film', name: 'alpine_v1_rough.mp4',      type: 'video',  parentId: 'bf-alpine-edits', size: 471859200,  modifiedAt: '2026-02-22T16:00:00Z', owner: 'Charlie' },
  { id: 'bf-alpine-v2',      workspaceId: 'byron-film', name: 'alpine_v2_colour.mp4',     type: 'video',  parentId: 'bf-alpine-edits', size: 545259520,  modifiedAt: '2026-02-24T10:00:00Z', owner: 'Charlie' },

  // Projects / Pacific Wellness
  { id: 'bf-p-wellness',       workspaceId: 'byron-film', name: 'Pacific Wellness', type: 'folder', parentId: 'bf-projects',      modifiedAt: '2026-02-22T14:00:00Z', owner: 'Charlie' },
  { id: 'bf-wellness-raw',     workspaceId: 'byron-film', name: 'Raw',              type: 'folder', parentId: 'bf-p-wellness',    modifiedAt: '2026-02-10T09:00:00Z', owner: 'Charlie' },
  { id: 'bf-wellness-finals',  workspaceId: 'byron-film', name: 'Finals',           type: 'folder', parentId: 'bf-p-wellness',    modifiedAt: '2026-02-22T14:00:00Z', owner: 'Charlie' },
  { id: 'bf-wellness-day1',    workspaceId: 'byron-film', name: 'wellness_shoot_day1.mp4',   type: 'video', parentId: 'bf-wellness-raw',    size: 3650722816, modifiedAt: '2026-02-10T18:00:00Z', owner: 'Charlie' },
  { id: 'bf-wellness-hero',    workspaceId: 'byron-film', name: 'hero_90s_final.mp4',        type: 'video', parentId: 'bf-wellness-finals', size: 220200960,  modifiedAt: '2026-02-22T14:00:00Z', owner: 'Charlie' },
  { id: 'bf-wellness-social',  workspaceId: 'byron-film', name: 'social_15s_x3.mp4',         type: 'video', parentId: 'bf-wellness-finals', size: 89128960,   modifiedAt: '2026-02-22T14:30:00Z', owner: 'Charlie' },

  // Projects / Byron Surf Festival
  { id: 'bf-p-surf',           workspaceId: 'byron-film', name: 'Byron Surf Festival',     type: 'folder', parentId: 'bf-projects', modifiedAt: '2026-02-15T09:00:00Z', owner: 'Charlie' },
  { id: 'bf-surf-highlights',  workspaceId: 'byron-film', name: 'surf_event_highlights.mp4', type: 'video', parentId: 'bf-p-surf', size: 1887436288, modifiedAt: '2026-02-14T20:00:00Z', owner: 'Charlie' },
  { id: 'bf-surf-brief',       workspaceId: 'byron-film', name: 'event_brief.pdf',            type: 'pdf',   parentId: 'bf-p-surf', size: 819200,     modifiedAt: '2026-01-25T10:00:00Z', owner: 'Charlie' },

  // Deliverables
  { id: 'bf-del-alpine',   workspaceId: 'byron-film', name: 'alpine_commercial_FINAL.mp4',      type: 'video', parentId: 'bf-deliverables', size: 293601280, modifiedAt: '2026-02-24T11:00:00Z', owner: 'Charlie' },
  { id: 'bf-del-wellness', workspaceId: 'byron-film', name: 'pacific_wellness_hero_FINAL.mp4',  type: 'video', parentId: 'bf-deliverables', size: 220200960, modifiedAt: '2026-02-22T15:00:00Z', owner: 'Charlie' },
  { id: 'bf-del-thumbs',   workspaceId: 'byron-film', name: 'alpine_thumbnails.zip',            type: 'zip',   parentId: 'bf-deliverables', size: 47185920,  modifiedAt: '2026-02-23T09:00:00Z', owner: 'Charlie' },

  // Contracts
  { id: 'bf-con-alpine',   workspaceId: 'byron-film', name: 'alpine_commercial_contract.pdf', type: 'pdf', parentId: 'bf-contracts', size: 430080, modifiedAt: '2026-01-15T10:00:00Z', owner: 'Charlie' },
  { id: 'bf-con-wellness', workspaceId: 'byron-film', name: 'pacific_wellness_agreement.pdf', type: 'pdf', parentId: 'bf-contracts', size: 389120, modifiedAt: '2026-02-08T10:00:00Z', owner: 'Charlie' },
  { id: 'bf-con-surf',     workspaceId: 'byron-film', name: 'surf_festival_invoice.pdf',      type: 'pdf', parentId: 'bf-contracts', size: 122880, modifiedAt: '2026-02-15T09:00:00Z', owner: 'Charlie' },

  // Assets
  { id: 'bf-brand',      workspaceId: 'byron-film', name: 'Brand Assets', type: 'folder', parentId: 'bf-assets', modifiedAt: '2026-01-30T11:00:00Z', owner: 'Charlie' },
  { id: 'bf-music',      workspaceId: 'byron-film', name: 'Music',        type: 'folder', parentId: 'bf-assets', modifiedAt: '2026-01-28T14:00:00Z', owner: 'Charlie' },
  { id: 'bf-brand-logo', workspaceId: 'byron-film', name: 'byron_film_logo.png', type: 'image', parentId: 'bf-brand', size: 2097152, modifiedAt: '2026-01-30T11:00:00Z', owner: 'Charlie' },
  { id: 'bf-brand-svg',  workspaceId: 'byron-film', name: 'logo_dark.svg',       type: 'image', parentId: 'bf-brand', size: 49152,   modifiedAt: '2026-01-30T11:00:00Z', owner: 'Charlie' },
  { id: 'bf-music-1',    workspaceId: 'byron-film', name: 'license_track_01.mp3', type: 'audio', parentId: 'bf-music', size: 8388608, modifiedAt: '2026-01-28T14:00:00Z', owner: 'Charlie' },
  { id: 'bf-music-2',    workspaceId: 'byron-film', name: 'ambient_loop.mp3',     type: 'audio', parentId: 'bf-music', size: 6291456, modifiedAt: '2026-01-28T14:30:00Z', owner: 'Charlie' },

  // ── KORUS ────────────────────────────────────────────────────────────
  // Root folders
  { id: 'ko-proposals', workspaceId: 'korus', name: 'Proposals', type: 'folder', parentId: null, modifiedAt: '2026-02-23T11:00:00Z', owner: 'Charlie' },
  { id: 'ko-reports',   workspaceId: 'korus', name: 'Reports',   type: 'folder', parentId: null, modifiedAt: '2026-02-20T16:00:00Z', owner: 'Charlie' },
  { id: 'ko-contracts', workspaceId: 'korus', name: 'Contracts', type: 'folder', parentId: null, modifiedAt: '2026-01-20T10:00:00Z', owner: 'Charlie' },
  { id: 'ko-marketing', workspaceId: 'korus', name: 'Marketing', type: 'folder', parentId: null, modifiedAt: '2026-02-15T09:00:00Z', owner: 'Charlie' },
  { id: 'ko-internal',  workspaceId: 'korus', name: 'Internal',  type: 'folder', parentId: null, modifiedAt: '2026-02-25T08:00:00Z', owner: 'Charlie' },

  // Proposals
  { id: 'ko-prop-fittech',     workspaceId: 'korus', name: 'q1_2026_proposal_fittech.docx',      type: 'doc', parentId: 'ko-proposals', size: 2411724, modifiedAt: '2026-02-20T11:00:00Z', owner: 'Charlie' },
  { id: 'ko-prop-healthworks', workspaceId: 'korus', name: 'healthworks_partnership_v2.docx',    type: 'doc', parentId: 'ko-proposals', size: 1887437, modifiedAt: '2026-02-18T14:00:00Z', owner: 'Charlie' },
  { id: 'ko-prop-zenflow',     workspaceId: 'korus', name: 'zenflow_onboarding_proposal.pdf',    type: 'pdf', parentId: 'ko-proposals', size: 3250585, modifiedAt: '2026-02-23T11:00:00Z', owner: 'Charlie' },

  // Reports
  { id: 'ko-rep-q4',       workspaceId: 'korus', name: 'q4_2025_revenue_report.xlsx',   type: 'spreadsheet', parentId: 'ko-reports', size: 1153433, modifiedAt: '2026-01-15T10:00:00Z', owner: 'Charlie' },
  { id: 'ko-rep-pipeline', workspaceId: 'korus', name: 'pipeline_summary_feb2026.xlsx', type: 'spreadsheet', parentId: 'ko-reports', size: 911360,  modifiedAt: '2026-02-20T16:00:00Z', owner: 'Charlie' },
  { id: 'ko-rep-strategic',workspaceId: 'korus', name: 'strategic_review_2026.pdf',     type: 'pdf',         parentId: 'ko-reports', size: 5452595, modifiedAt: '2026-02-10T10:00:00Z', owner: 'Charlie' },

  // Contracts
  { id: 'ko-con-fittech',    workspaceId: 'korus', name: 'fittech_services_agreement.pdf', type: 'pdf', parentId: 'ko-contracts', size: 696320, modifiedAt: '2026-01-10T10:00:00Z', owner: 'Charlie' },
  { id: 'ko-con-healthworks',workspaceId: 'korus', name: 'healthworks_nda.pdf',            type: 'pdf', parentId: 'ko-contracts', size: 215040, modifiedAt: '2026-01-15T10:00:00Z', owner: 'Charlie' },
  { id: 'ko-con-zenflow',    workspaceId: 'korus', name: 'zenflow_msa.pdf',                type: 'pdf', parentId: 'ko-contracts', size: 552960, modifiedAt: '2026-01-20T10:00:00Z', owner: 'Charlie' },

  // Marketing
  { id: 'ko-mkt-brand',     workspaceId: 'korus', name: 'Brand',     type: 'folder', parentId: 'ko-marketing', modifiedAt: '2026-02-15T09:00:00Z', owner: 'Charlie' },
  { id: 'ko-mkt-campaigns', workspaceId: 'korus', name: 'Campaigns', type: 'folder', parentId: 'ko-marketing', modifiedAt: '2026-02-10T11:00:00Z', owner: 'Charlie' },
  { id: 'ko-brand-logo',       workspaceId: 'korus', name: 'korus_logo_v3.png',   type: 'image', parentId: 'ko-mkt-brand',     size: 3145728, modifiedAt: '2026-02-15T09:00:00Z', owner: 'Charlie' },
  { id: 'ko-brand-guidelines', workspaceId: 'korus', name: 'brand_guidelines.pdf',type: 'pdf',   parentId: 'ko-mkt-brand',     size: 8388608, modifiedAt: '2026-02-14T10:00:00Z', owner: 'Charlie' },
  { id: 'ko-camp-q1',          workspaceId: 'korus', name: 'q1_campaign_brief.docx', type: 'doc', parentId: 'ko-mkt-campaigns', size: 1258291, modifiedAt: '2026-02-10T11:00:00Z', owner: 'Charlie' },

  // Internal
  { id: 'ko-int-handbook',  workspaceId: 'korus', name: 'team_handbook.pdf', type: 'pdf',         parentId: 'ko-internal', size: 4404019, modifiedAt: '2026-01-05T10:00:00Z', owner: 'Charlie' },
  { id: 'ko-int-budget',    workspaceId: 'korus', name: 'budget_2026.xlsx',  type: 'spreadsheet', parentId: 'ko-internal', size: 1572864, modifiedAt: '2026-02-25T08:00:00Z', owner: 'Charlie' },
  { id: 'ko-int-meetings',  workspaceId: 'korus', name: 'Meeting Notes',     type: 'folder',      parentId: 'ko-internal', modifiedAt: '2026-02-24T10:00:00Z', owner: 'Charlie' },
  { id: 'ko-meet-weekly',   workspaceId: 'korus', name: 'weekly_standup_feb2026.docx', type: 'doc', parentId: 'ko-int-meetings', size: 348160, modifiedAt: '2026-02-24T10:00:00Z', owner: 'Charlie' },
  { id: 'ko-meet-board',    workspaceId: 'korus', name: 'board_meeting_jan2026.docx',  type: 'doc', parentId: 'ko-int-meetings', size: 911360, modifiedAt: '2026-01-28T15:00:00Z', owner: 'Charlie' },
];
