import { Task, Project, Area, Contact } from '@/types';

export const MOCK_TASKS: Task[] = [
  // Byron Film tasks
  {
    id: 'task-1',
    workspaceId: 'byron-film',
    title: 'Scout locations for Alpine commercial',
    description: 'Need to find 3 mountain locations within 2hrs of Byron Bay',
    status: 'pre-prod',
    priority: 'high',
    dueDate: '2026-03-10',
    assignee: 'Charlie',
    tags: ['commercial', 'alpine'],
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-02-20T14:00:00Z',
  },
  {
    id: 'task-2',
    workspaceId: 'byron-film',
    title: 'Edit reel for Pacific Wellness campaign',
    description: 'Cut 90s hero video + 3x 15s socials',
    status: 'post-prod',
    priority: 'urgent',
    dueDate: '2026-03-05',
    assignee: 'Charlie',
    tags: ['wellness', 'social'],
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-22T16:00:00Z',
  },
  {
    id: 'task-3',
    workspaceId: 'byron-film',
    title: 'Invoice Byron Surf Festival',
    status: 'invoiced',
    priority: 'medium',
    tags: ['admin', 'invoice'],
    createdAt: '2026-02-15T08:00:00Z',
    updatedAt: '2026-02-15T08:00:00Z',
  },
  {
    id: 'task-4',
    workspaceId: 'byron-film',
    title: 'Concept development — Spring lookbook',
    status: 'backlog',
    priority: 'low',
    tags: ['creative', 'lookbook'],
    createdAt: '2026-02-18T11:00:00Z',
    updatedAt: '2026-02-18T11:00:00Z',
  },
  {
    id: 'task-5',
    workspaceId: 'byron-film',
    title: 'Drone footage review — Sunrise sessions',
    status: 'review',
    priority: 'high',
    dueDate: '2026-03-02',
    assignee: 'Charlie',
    tags: ['drone', 'review'],
    createdAt: '2026-02-20T09:00:00Z',
    updatedAt: '2026-02-24T12:00:00Z',
  },
  // KORUS tasks
  {
    id: 'task-6',
    workspaceId: 'korus',
    title: 'Meridian Group — initial call',
    description: 'First discovery call to qualify opportunity',
    status: 'lead',
    priority: 'medium',
    dueDate: '2026-03-01',
    assignee: 'Charlie',
    tags: ['enterprise'],
    createdAt: '2026-02-20T10:00:00Z',
    updatedAt: '2026-02-20T10:00:00Z',
  },
  {
    id: 'task-7',
    workspaceId: 'korus',
    title: 'Apex Partners — proposal deck',
    description: 'Prepare and send proposal for Q2 engagement',
    status: 'proposal',
    priority: 'urgent',
    dueDate: '2026-03-03',
    assignee: 'Charlie',
    tags: ['proposal', 'priority'],
    createdAt: '2026-02-18T09:00:00Z',
    updatedAt: '2026-02-24T15:00:00Z',
  },
  {
    id: 'task-8',
    workspaceId: 'korus',
    title: 'Solaris Tech — contract negotiation',
    status: 'negotiation',
    priority: 'high',
    dueDate: '2026-03-07',
    assignee: 'Charlie',
    tags: ['contract'],
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-02-23T11:00:00Z',
  },
  {
    id: 'task-9',
    workspaceId: 'korus',
    title: 'BlueSky Ventures — onboarding',
    status: 'won',
    priority: 'medium',
    tags: ['onboarding'],
    createdAt: '2026-02-10T09:00:00Z',
    updatedAt: '2026-02-20T14:00:00Z',
  },
  {
    id: 'task-10',
    workspaceId: 'korus',
    title: 'Redline Capital — qualify requirements',
    status: 'qualification',
    priority: 'high',
    dueDate: '2026-03-05',
    assignee: 'Charlie',
    tags: ['finance'],
    createdAt: '2026-02-22T09:00:00Z',
    updatedAt: '2026-02-22T09:00:00Z',
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    workspaceId: 'byron-film',
    name: 'Pacific Wellness Campaign',
    description: 'Full video production for Pacific Wellness brand',
    status: 'active',
    startDate: '2026-02-01',
    endDate: '2026-03-15',
    budget: 12000,
  },
  {
    id: 'proj-2',
    workspaceId: 'byron-film',
    name: 'Alpine Commercial Series',
    description: '3-part commercial series for outdoor brand',
    status: 'active',
    startDate: '2026-02-15',
    endDate: '2026-04-01',
    budget: 18000,
  },
  {
    id: 'proj-3',
    workspaceId: 'byron-film',
    name: 'Byron Surf Festival Coverage',
    description: 'Event coverage and highlight reel',
    status: 'completed',
    startDate: '2026-01-20',
    endDate: '2026-02-10',
    budget: 5500,
  },
  {
    id: 'proj-4',
    workspaceId: 'korus',
    name: 'Q1 Enterprise Push',
    description: 'Close 5 enterprise deals in Q1',
    status: 'active',
    startDate: '2026-01-01',
    endDate: '2026-03-31',
  },
];

export const MOCK_CONTACTS: Contact[] = [
  {
    id: 'contact-1',
    workspaceId: 'korus',
    name: 'Sarah Chen',
    email: 'sarah@apexpartners.com',
    company: 'Apex Partners',
    role: 'CEO',
    pipelineStage: 'proposal',
    tags: ['enterprise', 'priority'],
    lastContact: '2026-02-24',
  },
  {
    id: 'contact-2',
    workspaceId: 'korus',
    name: 'Marcus Webb',
    email: 'mwebb@solaristech.io',
    company: 'Solaris Tech',
    role: 'COO',
    pipelineStage: 'negotiation',
    tags: ['tech', 'contract'],
    lastContact: '2026-02-23',
  },
  {
    id: 'contact-3',
    workspaceId: 'korus',
    name: 'Priya Sharma',
    email: 'priya@blueskyventures.co',
    company: 'BlueSky Ventures',
    role: 'Partner',
    pipelineStage: 'won',
    tags: ['vc', 'won'],
    lastContact: '2026-02-20',
  },
];

export const KORUS_METRICS = {
  revenue: {
    current: 247500,
    previous: 198000,
    label: 'Revenue MTD',
  },
  projects: {
    active: 4,
    total: 12,
    label: 'Active Projects',
  },
  leads: {
    active: 7,
    qualified: 3,
    label: 'Active Leads',
  },
  wonDeals: {
    count: 3,
    value: 94000,
    label: 'Deals Won (Q1)',
  },
};
